sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: FTDl/UztEIX9mbHa9f528IE7tYLywp44C+PWqnfMU+fAeWGiAAPNu1wV8diEKYQpe5K0+Zef/qtdAWaOG9zTNVhDQEe2QBtC1t6RaTm2Lh5xMkdI14TSflE+NvTowgwrVtVxP+5Ppm5H3tESqyDdfFYPPROnQ6ueniyKcb7HB5Gkk6C96fdFFwC82kHqK5rnN7TLrU790Cz1hDwglujbDrZxEpfiMKQiFrQUYs5+IAia6EjJyOYcDMC3G7+e/eoJPAdHi+g+6ewm/pe1EmDSc/tKG7M7o92m28JkbYlQRE910iDCsVdyvt5BJQZaE5SscLqBMpLYr8Jky1MWJxEKmoGjwSQ53ADmacrD9miTZRRGa/R3Ki2D24TZ8SdJfCSrW72aOn8cEzv4LjFn18dNAoPZO2GpsfG6Wyz+YF+bKWxLdooaP79Wc3P71/yn8s8BwH+MycNKveX90gteHqx+1HC17Q61LeXbnENv69cCn3TTeenT0NJosH5+wSTmgm5X0M0cFynMwa88JO3qvODA3k7xkgYU2ENFp3loz46zjEMQ7j8+aWUrjVvmdNaN3C4J/DqFgUiUjSWjB7txkej7xO+EOqTGirzPoilaLZJZZuKzKmIqJ8ST5URtpFmspir50Yq6R1PW+EaaNy4o8MuYEcmNdwWZ8fsWaiExdXDuQF4=
  - secure: Etfq2868M4JoJ2h0I6NVgox/YOBhq/wozbrbW879RCxSzcI0Tb5bYnWGRyFf2qQdmiwlhfe4Lo0CB8v7htJ3MirraDTaujCNrosD/Qa5oR9RuS0nRTjFkzoEMTbR8wXDa6tpp/Y0l7Dyc0ZriC4BBkRfkMZx4ZYMPampUHPkmbpe7VXMnLef/htvJM8rs9Vy+VYqMjAgRxCFZVXUtjFgID9Pf0g252lAiVglz3cQpb4BvyaXlsa2Kb3BuI+Q+Mne3T5yHfLfLY6qDcLeBK2NIXkVKRVpkkJHixFsSGBU4X1+4x/S/049bQxWnJkEVwzeQ9dLMqlT/R50tKcRDqa6mCWFibC9gyphABM82M2mBB0rkLaK+7fIOcZSj/9q/MXIPEaxyW1ENEbUsm097Bzm3l4Xtsx86iY76upe4Q32/qiW6raM0zhIoaSunwrZTywZ77cg0GpSByfoMI14+mVtar1X+2eBOFH1a1N/M1IAX1jZRES6d5rmOOvCRF+weXpdyvHQIdIG4xhoCN3JJzSd2MS1Tjh5gg3AYiERBrkfTQBLlIUvKsn3QNVIxtbseuIABUPmHJkk3YSDgBfLv2+Q2/pvChnwypVbyXJOiUbckybr4T0j67NeYW3TyMemHC5AP5QJvvl/UqmGOBKHzBu3+OC3XtCsEEM07c78x9Y4xws=
